[package]
name = "geotrick"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
cortex-m-semihosting = "0.5.0"
panic-halt = "0.2.0"
panic-semihosting = "0.6.0"

[[bin]]
name = "geotrick"
test = false
bench = false
